import {
  AnimeSeries,
  Book,
  Genre,
  Studio,
} from '../types';

export const INITIAL_GENRES: Genre[] = [
  { id: 1, name: 'Fantasy' },
  { id: 2, name: 'Adventure' },
  { id: 3, name: 'Sci-Fi' },
  { id: 4, name: 'Psychological' },
  { id: 5, name: 'Drama' },
  { id: 6, name: 'Slice of Life' },
  { id: 7, name: 'Philosophy' },
  { id: 8, name: 'History' },
  { id: 9, name: 'Action' },
  { id: 10, name: 'Mystery' },
];

export const INITIAL_STUDIOS: Studio[] = [
  { id: 1, name: 'Madhouse' },
  { id: 2, name: 'Wit Studio' },
  { id: 3, name: 'MAPPA' },
  { id: 4, name: 'White Fox' },
  { id: 5, name: 'Kyoto Animation' },
  { id: 6, name: 'Bones' },
  { id: 7, name: 'ufotable' },
];

export const INITIAL_SERIES: AnimeSeries[] = [
  {
    id: 1,
    title: "Frieren: Beyond Journey's End",
    image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    created_at: '2025-10-15T12:00:00Z',
    genres: [
      { id: 1, name: 'Fantasy' },
      { id: 2, name: 'Adventure' },
      { id: 5, name: 'Drama' },
    ],
    studios: [{ id: 1, name: 'Madhouse' }],
    seasons: [
      {
        id: 1,
        series: 1,
        series_title: "Frieren: Beyond Journey's End",
        title: 'Season 1',
        season_number: 1,
        status: 'COMPLETED',
        rating: 10,
        progress: 28,
        total_episodes: 28,
        image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        start_date: '2025-10-15',
        finish_date: '2025-11-20',
        notes:
          'A profound lesson on the relativity of time. When lifespan spans a millennium, moments feel transient until someone is gone. Himmel taught Frieren that even brief shared journeys shape our human warmth. It reminded me never to postpone expressing care to those around me.',
        created_at: '2025-10-15T12:00:00Z',
        studios: [{ id: 1, name: 'Madhouse' }],
        episode_notes: [
          {
            id: 1,
            season: 1,
            season_title: 'Season 1',
            episode_number: 1,
            episode_title: "The Journey's End",
            note: 'Realizing that 10 years of adventuring was barely a drop in an elf lifespan, yet it became the emotional anchor for the rest of her existence.',
            rating: 10,
            image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
            created_at: '2025-10-15T12:30:00Z',
          },
          {
            id: 2,
            season: 1,
            season_title: 'Season 1',
            episode_number: 8,
            episode_title: 'Frieren the Slayer',
            note: 'A chilling yet composed demonstration of absolute dedication to aura concealment and patience over centuries.',
            rating: 9,
            created_at: '2025-10-22T12:30:00Z',
          },
          {
            id: 3,
            season: 1,
            season_title: 'Season 1',
            episode_number: 28,
            episode_title: 'It Would Be Embarrassing When We Meet Again',
            note: "A bittersweet farewell. An adventure doesn't truly end as long as the memories keep guiding you forward.",
            rating: 10,
            created_at: '2025-11-20T12:30:00Z',
          },
        ],
        rewatches: [
          {
            id: 1,
            season: 1,
            movie: null,
            release_title: 'Season 1',
            start_date: '2026-04-01',
            finish_date: '2026-04-12',
            rating: 10,
            notes:
              "Rewatching with a slower mindset. Paying close attention to how Himmel's words guide Frieren's quiet patience with Fern and Stark.",
          },
        ],
      },
    ],
    movies: [],
    favorite_characters: [
      {
        id: 1,
        series: 1,
        series_title: "Frieren: Beyond Journey's End",
        name: 'Himmel the Hero',
        image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        why: 'He never took for granted that life is short. He deliberately erected statues not out of narcissism, but so Frieren would never feel lonely when everyone else was gone.',
      },
    ],
  },
  {
    id: 2,
    title: 'Attack on Titan',
    image_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    created_at: '2023-01-10T08:00:00Z',
    genres: [
      { id: 9, name: 'Action' },
      { id: 5, name: 'Drama' },
      { id: 1, name: 'Fantasy' },
      { id: 10, name: 'Mystery' },
    ],
    studios: [
      { id: 2, name: 'Wit Studio' },
      { id: 3, name: 'MAPPA' },
    ],
    seasons: [
      {
        id: 2,
        series: 2,
        series_title: 'Attack on Titan',
        title: 'Season 1',
        season_number: 1,
        status: 'COMPLETED',
        rating: 9,
        progress: 25,
        total_episodes: 25,
        image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        start_date: '2023-01-10',
        finish_date: '2023-02-01',
        notes: 'The visceral terror of powerlessness within the walls and humanity fierce instinct to fight.',
        created_at: '2023-01-10T08:00:00Z',
        studios: [{ id: 2, name: 'Wit Studio' }],
      },
      {
        id: 3,
        series: 2,
        series_title: 'Attack on Titan',
        title: 'Season 2',
        season_number: 2,
        status: 'COMPLETED',
        rating: 9,
        progress: 12,
        total_episodes: 12,
        image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        start_date: '2023-02-05',
        finish_date: '2023-02-20',
        notes: 'Betrayal, loyalty, and the revelation that enemies are people we once broke bread with.',
        created_at: '2023-02-05T08:00:00Z',
        studios: [{ id: 2, name: 'Wit Studio' }],
      },
      {
        id: 4,
        series: 2,
        series_title: 'Attack on Titan',
        title: 'Season 3',
        season_number: 3,
        status: 'COMPLETED',
        rating: 10,
        progress: 22,
        total_episodes: 22,
        image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
        start_date: '2023-03-01',
        finish_date: '2023-03-28',
        notes: "Erwin's charge: giving meaning to the lives of fallen comrades. Beyond the sea lies not freedom, but complex truth.",
        created_at: '2023-03-01T08:00:00Z',
        studios: [{ id: 2, name: 'Wit Studio' }],
      },
      {
        id: 5,
        series: 2,
        series_title: 'Attack on Titan',
        title: 'The Final Season',
        season_number: 4,
        status: 'COMPLETED',
        rating: 10,
        progress: 28,
        total_episodes: 28,
        image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-01-15',
        finish_date: '2024-03-10',
        notes: 'The devastating cycle of hatred and generational trauma. There are no villains on either side of the sea—only humans trapped by history.',
        created_at: '2024-01-15T08:00:00Z',
        studios: [{ id: 3, name: 'MAPPA' }],
      },
    ],
    movies: [],
    favorite_characters: [
      {
        id: 2,
        series: 2,
        series_title: 'Attack on Titan',
        name: 'Erwin Smith',
        image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        why: "The ultimate leader who bore the weight of deception to charge into the unknown, giving purpose to every soldier's sacrifice.",
      },
    ],
  },
  {
    id: 3,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    created_at: '2024-06-01T08:00:00Z',
    genres: [
      { id: 9, name: 'Action' },
      { id: 1, name: 'Fantasy' },
      { id: 2, name: 'Adventure' },
    ],
    studios: [{ id: 7, name: 'ufotable' }],
    seasons: [
      {
        id: 6,
        series: 3,
        series_title: 'Demon Slayer: Kimetsu no Yaiba',
        title: 'Unwavering Resolve Arc',
        season_number: 1,
        status: 'COMPLETED',
        rating: 9,
        progress: 26,
        total_episodes: 26,
        image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-06-01',
        finish_date: '2024-06-20',
        notes: "Tanjiro's unwavering compassion even towards demons who caused him immense suffering.",
        created_at: '2024-06-01T08:00:00Z',
        studios: [{ id: 7, name: 'ufotable' }],
      },
      {
        id: 7,
        series: 3,
        series_title: 'Demon Slayer: Kimetsu no Yaiba',
        title: 'Entertainment District Arc',
        season_number: 2,
        status: 'COMPLETED',
        rating: 9,
        progress: 11,
        total_episodes: 11,
        image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-08-01',
        finish_date: '2024-08-15',
        notes: 'Spectacular visual storytelling emphasizing perseverance when pushing past physical limits.',
        created_at: '2024-08-01T08:00:00Z',
        studios: [{ id: 7, name: 'ufotable' }],
      },
    ],
    movies: [
      {
        id: 1,
        series: 3,
        series_title: 'Demon Slayer: Kimetsu no Yaiba',
        title: 'Mugen Train',
        status: 'COMPLETED',
        rating: 10,
        progress_minutes: 117,
        total_minutes: 117,
        image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-07-01',
        finish_date: '2024-07-01',
        notes: "'Set your heart ablaze.' Rengoku demonstrated what it means to fulfill one's duty and protect the weak with warmth and courage until the very end.",
        created_at: '2024-07-01T08:00:00Z',
        studios: [{ id: 7, name: 'ufotable' }],
        rewatches: [
          {
            id: 2,
            season: null,
            movie: 1,
            release_title: 'Mugen Train',
            start_date: '2025-01-15',
            finish_date: '2025-01-15',
            rating: 10,
            notes: "Revisited Rengoku's battle with Akaza. His resolve and optimism shine even brighter on rewatch.",
          },
        ],
      },
    ],
    favorite_characters: [],
  },
  {
    id: 4,
    title: 'Steins;Gate',
    image_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    created_at: '2024-05-01T14:30:00Z',
    genres: [
      { id: 3, name: 'Sci-Fi' },
      { id: 4, name: 'Psychological' },
      { id: 5, name: 'Drama' },
    ],
    studios: [{ id: 4, name: 'White Fox' }],
    seasons: [
      {
        id: 8,
        series: 4,
        series_title: 'Steins;Gate',
        title: 'Season 1',
        season_number: 1,
        status: 'COMPLETED',
        rating: 10,
        progress: 24,
        total_episodes: 24,
        image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-05-01',
        finish_date: '2024-05-18',
        notes:
          'Consequences of obsession and the weight of bearing sole memory of multiple timelines. The importance of sacrifice and unwavering loyalty to friends.',
        created_at: '2024-05-01T14:30:00Z',
        studios: [{ id: 4, name: 'White Fox' }],
        rewatches: [
          {
            id: 3,
            season: 8,
            movie: null,
            release_title: 'Season 1',
            start_date: '2026-02-10',
            finish_date: '2026-02-18',
            rating: 10,
            notes:
              "Second pass hit far harder knowing Okabe's eventual despair from the opening episode. The subtle foreshadowing in Kurisu's early dialogues made the whole sacrifice arc unforgettable.",
          },
        ],
      },
    ],
    movies: [
      {
        id: 2,
        series: 4,
        series_title: 'Steins;Gate',
        title: 'Load Region of Déjà Vu',
        status: 'COMPLETED',
        rating: 8,
        progress_minutes: 90,
        total_minutes: 90,
        image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        start_date: '2024-06-01',
        finish_date: '2024-06-01',
        notes: "Kurisu's perspective bearing the weight of rescuing Okabe from the R worldline.",
        created_at: '2024-06-01T14:30:00Z',
        studios: [{ id: 4, name: 'White Fox' }],
      },
    ],
    favorite_characters: [
      {
        id: 3,
        series: 4,
        series_title: 'Steins;Gate',
        name: 'Rintaro Okabe',
        image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        why: 'Willing to endure countless cycles of psychological trauma to protect the worldline where everyone he loves survives.',
      },
      {
        id: 4,
        series: 4,
        series_title: 'Steins;Gate',
        name: 'Kurisu Makise',
        image_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        why: 'Brilliant intellect combined with genuine emotional vulnerability and selflessness.',
      },
    ],
  },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 1,
    title: 'Dune',
    author: 'Frank Herbert',
    status: 'COMPLETED',
    rating: 9,
    progress: 688,
    total_pages: 688,
    start_date: '2025-06-01',
    finish_date: '2025-07-15',
    notes:
      'A masterclass warning against messianic leaders. Charisma combined with ecological and religious dogmatism creates uncontrollable momentum that sweeps even well-intentioned heroes into tragedy.',
    created_at: '2025-06-01T12:00:00Z',
    genres: [
      { id: 3, name: 'Sci-Fi' },
      { id: 7, name: 'Philosophy' },
    ],
  },
  {
    id: 2,
    title: 'Atomic Habits',
    author: 'James Clear',
    status: 'COMPLETED',
    rating: 8,
    progress: 320,
    total_pages: 320,
    start_date: '2025-08-01',
    finish_date: '2025-08-14',
    notes:
      'You do not rise to the level of your goals; you fall to the level of your systems. Small 1% compounding daily adjustments beat sporadic bursts of willpower every single time.',
    created_at: '2025-08-01T09:00:00Z',
    genres: [
      { id: 4, name: 'Psychological' },
      { id: 7, name: 'Philosophy' },
    ],
  },
  {
    id: 3,
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    status: 'READING',
    rating: 9,
    progress: 185,
    total_pages: 303,
    start_date: '2026-08-10',
    finish_date: null,
    notes:
      "Exploration of loneliness, sacrifice, and the unique human essence from an artificial friend's observant and gentle viewpoint. Is the human heart something that can truly be replicated?",
    created_at: '2026-08-10T14:00:00Z',
    genres: [
      { id: 3, name: 'Sci-Fi' },
      { id: 5, name: 'Drama' },
      { id: 7, name: 'Philosophy' },
    ],
  },
  {
    id: 4,
    title: 'Meditations',
    author: 'Marcus Aurelius',
    status: 'PLAN_TO_READ',
    rating: null,
    progress: 0,
    total_pages: 254,
    start_date: null,
    finish_date: null,
    notes: 'Personal journal of Roman Emperor on stoicism, duty, and maintaining mental equilibrium in turmoil.',
    created_at: '2026-08-15T10:00:00Z',
    genres: [{ id: 7, name: 'Philosophy' }],
  },
];
