# Generated by Django 6.1 on 2026-08-21 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('WATCHING', 'Watching'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('DROPPED', 'Dropped'), ('PLAN_TO_WATCH', 'Plan to Watch')], default='PLAN_TO_WATCH', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('progress', models.PositiveIntegerField(default=0, help_text='Current episode progress')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Anime',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Studio',
                'verbose_name_plural': 'Studios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('why', models.TextField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_characters', to='animeLog.anime')),
            ],
            options={
                'verbose_name': 'Favorite Character',
                'verbose_name_plural': 'Favorite Characters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('READING', 'Reading'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('DROPPED', 'Dropped'), ('PLAN_TO_READ', 'Plan to Read')], default='PLAN_TO_READ', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('progress', models.PositiveIntegerField(default=0, help_text='Current page/chapter progress')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='animeLog.genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime', to='animeLog.genre'),
        ),
        migrations.CreateModel(
            name='Rewatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rewatch rating score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewatches', to='animeLog.anime')),
            ],
            options={
                'verbose_name': 'Rewatch',
                'verbose_name_plural': 'Rewatches',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='anime', to='animeLog.studio'),
        ),
    ]
