# Generated by Django 6.1 on 2026-08-24 03:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeLog', '0004_polymorphic_rewatch'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rewatch',
            new_name='animeLog_re_content_f25c01_idx',
            old_name='animeLog_re_content_73926f_idx',
        ),
        migrations.AddField(
            model_name='rewatch',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional episode number when rewatching a specific episode of a season', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rewatch',
            name='episode_title',
            field=models.CharField(blank=True, help_text='Optional episode title or note for this episode rewatch pass', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rewatch',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'animeLog'), ('model__in', ['animeseries', 'animeseason', 'animemovie'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
