# Generated by Django 6.1 on 2026-08-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeLog', '0005_rename_animelog_re_content_73926f_idx_animelog_re_content_f25c01_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeseries',
            name='japanese_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animeseries',
            name='romaji_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
