# Generated by Django 6.1 on 2026-08-24 21:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_character_cover_images(apps, schema_editor):
    FavoriteCharacter = apps.get_model('animeLog', 'FavoriteCharacter')
    for character in FavoriteCharacter.objects.all():
        first_img = character.images.first()
        if first_img and not character.cover_image_id:
            character.cover_image = first_img
            character.save(update_fields=['cover_image'])


class Migration(migrations.Migration):

    dependencies = [
        ('animeLog', '0006_animeseries_japanese_title_animeseries_romaji_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecharacter',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_characters_cover', to='animeLog.image'),
        ),
        migrations.RunPython(backfill_character_cover_images, migrations.RunPython.noop),
    ]
